export * from './auditlog.service';
import { AuditlogService } from './auditlog.service';
export * from './dataPermission.service';
import { DataPermissionService } from './dataPermission.service';
export * from './datamodel.service';
import { DatamodelService } from './datamodel.service';
export * from './file.service';
import { FileService } from './file.service';
export * from './menu.service';
import { MenuService } from './menu.service';
export * from './pemgroup.service';
import { PemgroupService } from './pemgroup.service';
export * from './rule.service';
import { RuleService } from './rule.service';
export * from './scope.service';
import { ScopeService } from './scope.service';
export * from './sysrole.service';
import { SysroleService } from './sysrole.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AuditlogService, DataPermissionService, DatamodelService, FileService, MenuService, PemgroupService, RuleService, ScopeService, SysroleService, UserService];
