/**
 * anran-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MoneyEvent { 
    readonly createdDate?: Date;
    readonly modifiedDate?: Date;
    readonly createdBy?: string;
    readonly modifiedBy?: string;
    readonly id?: string;
    transactionType?: MoneyEvent.TransactionTypeEnum;
    fromName?: string;
    fromAccount?: string;
    toName?: string;
    toAccount?: string;
    amount?: number;
    currency?: string;
    date?: Date;
}
export namespace MoneyEvent {
    export type TransactionTypeEnum = 'BANK' | 'CASH';
    export const TransactionTypeEnum = {
        BANK: 'BANK' as TransactionTypeEnum,
        CASH: 'CASH' as TransactionTypeEnum
    };
}