/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ScopeRepresentation } from './scopeRepresentation';

export interface ResourceRepresentation { 
    id?: string;
    attributes?: { [key: string]: any; };
    displayName?: string;
    iconUri?: string;
    name?: string;
    ownerManagedAccess?: boolean;
    scopes?: Array<ScopeRepresentation>;
    type?: string;
    uris?: Array<string>;
}