export * from './authorization.service';
import { AuthorizationService } from './authorization.service';
export * from './batch.service';
import { BatchService } from './batch.service';
export * from './condition.service';
import { ConditionService } from './condition.service';
export * from './decisionDefinition.service';
import { DecisionDefinitionService } from './decisionDefinition.service';
export * from './decisionRequirementsDefinition.service';
import { DecisionRequirementsDefinitionService } from './decisionRequirementsDefinition.service';
export * from './deployment.service';
import { DeploymentService } from './deployment.service';
export * from './engine.service';
import { EngineService } from './engine.service';
export * from './eventSubscription.service';
import { EventSubscriptionService } from './eventSubscription.service';
export * from './execution.service';
import { ExecutionService } from './execution.service';
export * from './externalTask.service';
import { ExternalTaskService } from './externalTask.service';
export * from './filter.service';
import { FilterService } from './filter.service';
export * from './group.service';
import { GroupService } from './group.service';
export * from './historicActivityInstance.service';
import { HistoricActivityInstanceService } from './historicActivityInstance.service';
export * from './historicBatch.service';
import { HistoricBatchService } from './historicBatch.service';
export * from './historicDecisionDefinition.service';
import { HistoricDecisionDefinitionService } from './historicDecisionDefinition.service';
export * from './historicDecisionInstance.service';
import { HistoricDecisionInstanceService } from './historicDecisionInstance.service';
export * from './historicDecisionRequirementsDefinition.service';
import { HistoricDecisionRequirementsDefinitionService } from './historicDecisionRequirementsDefinition.service';
export * from './historicDetail.service';
import { HistoricDetailService } from './historicDetail.service';
export * from './historicExternalTaskLog.service';
import { HistoricExternalTaskLogService } from './historicExternalTaskLog.service';
export * from './historicIdentityLinkLog.service';
import { HistoricIdentityLinkLogService } from './historicIdentityLinkLog.service';
export * from './historicIncident.service';
import { HistoricIncidentService } from './historicIncident.service';
export * from './historicJobLog.service';
import { HistoricJobLogService } from './historicJobLog.service';
export * from './historicProcessDefinition.service';
import { HistoricProcessDefinitionService } from './historicProcessDefinition.service';
export * from './historicProcessInstance.service';
import { HistoricProcessInstanceService } from './historicProcessInstance.service';
export * from './historicTaskInstance.service';
import { HistoricTaskInstanceService } from './historicTaskInstance.service';
export * from './historicUserOperationLog.service';
import { HistoricUserOperationLogService } from './historicUserOperationLog.service';
export * from './historicVariableInstance.service';
import { HistoricVariableInstanceService } from './historicVariableInstance.service';
export * from './historyCleanup.service';
import { HistoryCleanupService } from './historyCleanup.service';
export * from './identity.service';
import { IdentityService } from './identity.service';
export * from './incident.service';
import { IncidentService } from './incident.service';
export * from './job.service';
import { JobService } from './job.service';
export * from './jobDefinition.service';
import { JobDefinitionService } from './jobDefinition.service';
export * from './message.service';
import { MessageService } from './message.service';
export * from './metrics.service';
import { MetricsService } from './metrics.service';
export * from './migration.service';
import { MigrationService } from './migration.service';
export * from './modification.service';
import { ModificationService } from './modification.service';
export * from './processDefinition.service';
import { ProcessDefinitionService } from './processDefinition.service';
export * from './processInstance.service';
import { ProcessInstanceService } from './processInstance.service';
export * from './schemaLog.service';
import { SchemaLogService } from './schemaLog.service';
export * from './signal.service';
import { SignalService } from './signal.service';
export * from './task.service';
import { TaskService } from './task.service';
export * from './taskAttachment.service';
import { TaskAttachmentService } from './taskAttachment.service';
export * from './taskComment.service';
import { TaskCommentService } from './taskComment.service';
export * from './taskIdentityLink.service';
import { TaskIdentityLinkService } from './taskIdentityLink.service';
export * from './taskLocalVariable.service';
import { TaskLocalVariableService } from './taskLocalVariable.service';
export * from './taskVariable.service';
import { TaskVariableService } from './taskVariable.service';
export * from './telemetry.service';
import { TelemetryService } from './telemetry.service';
export * from './tenant.service';
import { TenantService } from './tenant.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './variableInstance.service';
import { VariableInstanceService } from './variableInstance.service';
export * from './version.service';
import { VersionService } from './version.service';
export const APIS = [AuthorizationService, BatchService, ConditionService, DecisionDefinitionService, DecisionRequirementsDefinitionService, DeploymentService, EngineService, EventSubscriptionService, ExecutionService, ExternalTaskService, FilterService, GroupService, HistoricActivityInstanceService, HistoricBatchService, HistoricDecisionDefinitionService, HistoricDecisionInstanceService, HistoricDecisionRequirementsDefinitionService, HistoricDetailService, HistoricExternalTaskLogService, HistoricIdentityLinkLogService, HistoricIncidentService, HistoricJobLogService, HistoricProcessDefinitionService, HistoricProcessInstanceService, HistoricTaskInstanceService, HistoricUserOperationLogService, HistoricVariableInstanceService, HistoryCleanupService, IdentityService, IncidentService, JobService, JobDefinitionService, MessageService, MetricsService, MigrationService, ModificationService, ProcessDefinitionService, ProcessInstanceService, SchemaLogService, SignalService, TaskService, TaskAttachmentService, TaskCommentService, TaskIdentityLinkService, TaskLocalVariableService, TaskVariableService, TelemetryService, TenantService, UserService, VariableInstanceService, VersionService];
