/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Project } from './project';

export interface TeamMember { 
    type?: TeamMember.TypeEnum;
    project?: Project;
    projectId?: string;
    fanhao?: string;
    name?: string;
    idcardType?: string;
    idcardNumber?: string;
    age?: number;
    gender?: TeamMember.GenderEnum;
    provinceId?: string;
    chianSailboatId?: string;
    remark?: string;
}
export namespace TeamMember {
    export type TypeEnum = 'LEADER' | 'COACH' | 'ATHLETE' | 'WORKER';
    export const TypeEnum = {
        LEADER: 'LEADER' as TypeEnum,
        COACH: 'COACH' as TypeEnum,
        ATHLETE: 'ATHLETE' as TypeEnum,
        WORKER: 'WORKER' as TypeEnum
    };
    export type GenderEnum = 'MALE' | 'FEMALE';
    export const GenderEnum = {
        MALE: 'MALE' as GenderEnum,
        FEMALE: 'FEMALE' as GenderEnum
    };
}