/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.19.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DecisionDefinitionDto { 
    /**
     * The id of the decision definition
     */
    id?: string;
    /**
     * The key of the decision definition, i.e., the id of the DMN 1.0 XML decision definition.
     */
    key?: string;
    /**
     * The category of the decision definition.
     */
    category?: string;
    /**
     * The name of the decision definition.
     */
    name?: string;
    /**
     * The version of the decision definition that the engine assigned to it.
     */
    version?: number;
    /**
     * The file name of the decision definition.
     */
    resource?: string;
    /**
     * The deployment id of the decision definition.
     */
    deploymentId?: string;
    /**
     * The tenant id of the decision definition.
     */
    tenantId?: string;
    /**
     * The id of the decision requirements definition this decision definition belongs to.
     */
    decisionRequirementsDefinitionId?: string;
    /**
     * The key of the decision requirements definition this decision definition belongs to.
     */
    decisionRequirementsDefinitionKey?: string;
    /**
     * History time to live value of the decision definition. Is used within [History cleanup](https://docs.camunda.org/manual/7.19/user-guide/process-engine/history/#history-cleanup).
     */
    historyTimeToLive?: number;
    /**
     * The version tag of the decision definition.
     */
    versionTag?: string;
}