/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.19.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FilterDto { 
    /**
     * The id of the filter.
     */
    id?: string;
    /**
     * The resource type of the filter.
     */
    resourceType?: string;
    /**
     * The name of the filter.
     */
    name?: string;
    /**
     * The user id of the owner of the filter.
     */
    owner?: string;
    /**
     * The query of the filter as a JSON object.
     */
    query?: any;
    /**
     * The properties of a filter as a JSON object.
     */
    properties?: any;
    /**
     *  The number of items matched by the filter itself. Note: Only exists if the query parameter `itemCount` was set to `true`
     */
    itemCount?: number;
}