/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.19.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupQueryDtoSorting } from './groupQueryDtoSorting';

/**
 * A group instance query which defines a list of group instances
 */
export interface GroupQueryDto { 
    /**
     * Filter by the id of the group.
     */
    id?: string;
    /**
     * Filter by a JSON string array of group ids.
     */
    idIn?: Array<string>;
    /**
     * Filter by the name of the group.
     */
    name?: string;
    /**
     * Filter by the name that the parameter is a substring of.
     */
    nameLike?: string;
    /**
     * Filter by the type of the group.
     */
    type?: string;
    /**
     * Only retrieve groups where the given user id is a member of.
     */
    member?: string;
    /**
     * Only retrieve groups which are members of the given tenant.
     */
    memberOfTenant?: string;
    /**
     * Apply sorting of the result
     */
    sorting?: Array<GroupQueryDtoSorting>;
}