/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.19.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface HistoricJobLogDto { 
    /**
     * The id of the log entry.
     */
    id?: string;
    /**
     * The time when the log entry has been written.
     */
    timestamp?: Date;
    /**
     * The time after which the log entry should be removed by the History Cleanup job. Default format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`. For further info see the [docs](https://docs.camunda.org/manual/7.19/reference/rest/overview/date-format/)
     */
    removalTime?: Date;
    /**
     * The id of the associated job.
     */
    jobId?: string;
    /**
     * The date on which the associated job is supposed to be processed.
     */
    jobDueDate?: Date;
    /**
     * The number of retries the associated job has left.
     */
    jobRetries?: number;
    /**
     * The execution priority the job had when the log entry was created.
     */
    jobPriority?: number;
    /**
     * The message of the exception that occurred by executing the associated job.
     */
    jobExceptionMessage?: string;
    /**
     * The id of the activity on which the last exception occurred by executing the associated job.
     */
    failedActivityId?: string;
    /**
     * The id of the job definition on which the associated job was created.
     */
    jobDefinitionId?: string;
    /**
     * The job definition type of the associated job. See the [User Guide](https://docs.camunda.org/manual/7.19/user-guide/process-engine/the-job-executor/#job-creation) for more information about job definition types.
     */
    jobDefinitionType?: string;
    /**
     * The job definition configuration type of the associated job.
     */
    jobDefinitionConfiguration?: string;
    /**
     * The id of the activity on which the associated job was created.
     */
    activityId?: string;
    /**
     * The execution id on which the associated job was created.
     */
    executionId?: string;
    /**
     * The id of the process instance on which the associated job was created.
     */
    processInstanceId?: string;
    /**
     * The id of the process definition which the associated job belongs to.
     */
    processDefinitionId?: string;
    /**
     * The key of the process definition which the associated job belongs to.
     */
    processDefinitionKey?: string;
    /**
     * The id of the deployment which the associated job belongs to.
     */
    deploymentId?: string;
    /**
     * The process instance id of the root process instance that initiated the process which the associated job belongs to.
     */
    rootProcessInstanceId?: string;
    /**
     * The id of the tenant that this historic job log entry belongs to.
     */
    tenantId?: string;
    /**
     *  The name of the host of the Process Engine where the job of this historic job log entry was executed.
     */
    hostname?: string;
    /**
     * A flag indicating whether this log represents the creation of the associated job.
     */
    creationLog?: boolean;
    /**
     * A flag indicating whether this log represents the failed execution of the associated job.
     */
    failureLog?: boolean;
    /**
     * A flag indicating whether this log represents the successful execution of the associated job.
     */
    successLog?: boolean;
    /**
     * A flag indicating whether this log represents the deletion of the associated job.
     */
    deletionLog?: boolean;
}