/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.19.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface JobQueryDtoSorting { 
    /**
     * Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
     */
    sortBy?: JobQueryDtoSorting.SortByEnum;
    /**
     * Sort the results in a given order. Values may be `asc` for ascending order or `desc` for descending order. Must be used in conjunction with the sortBy parameter.
     */
    sortOrder?: JobQueryDtoSorting.SortOrderEnum;
}
export namespace JobQueryDtoSorting {
    export type SortByEnum = 'jobId' | 'executionId' | 'processInstanceId' | 'processDefinitionId' | 'processDefinitionKey' | 'jobPriority' | 'jobRetries' | 'jobDueDate' | 'tenantId';
    export const SortByEnum = {
        JobId: 'jobId' as SortByEnum,
        ExecutionId: 'executionId' as SortByEnum,
        ProcessInstanceId: 'processInstanceId' as SortByEnum,
        ProcessDefinitionId: 'processDefinitionId' as SortByEnum,
        ProcessDefinitionKey: 'processDefinitionKey' as SortByEnum,
        JobPriority: 'jobPriority' as SortByEnum,
        JobRetries: 'jobRetries' as SortByEnum,
        JobDueDate: 'jobDueDate' as SortByEnum,
        TenantId: 'tenantId' as SortByEnum
    };
    export type SortOrderEnum = 'asc' | 'desc';
    export const SortOrderEnum = {
        Asc: 'asc' as SortOrderEnum,
        Desc: 'desc' as SortOrderEnum
    };
}