/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.19.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MigrationInstructionDto } from './migrationInstructionDto';

export interface MigrationInstructionValidationReportDto { 
    instruction?: MigrationInstructionDto;
    /**
     * A list of instruction validation report messages.
     */
    failures?: Array<string>;
}