/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.19.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A JSON object with the following properties:
 */
export interface RedeploymentDto { 
    /**
     * A list of deployment resource ids to re-deploy.
     */
    resourceIds?: Array<string>;
    /**
     * A list of deployment resource names to re-deploy.
     */
    resourceNames?: Array<string>;
    /**
     * Sets the source of the deployment.
     */
    source?: string;
}