/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.19.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TelemetryLicenseKeyDto { 
    /**
     * The name of the customer the license was issued for.
     */
    customer?: string;
    /**
     * The license type.
     */
    type?: string;
    /**
     * The expiration date of the license.
     */
    validUntil?: string;
    /**
     * Flag that indicates if the license is unlimited.
     */
    unlimited?: boolean;
    /**
     * A map of features included in the license.
     */
    features?: { [key: string]: string; };
    /**
     * The raw license information.
     */
    raw?: string;
}