export * from './auditlog.service';
import { AuditlogService } from './auditlog.service';
export * from './dataOrganization.service';
import { DataOrganizationService } from './dataOrganization.service';
export * from './dataPermission.service';
import { DataPermissionService } from './dataPermission.service';
export * from './datamodel.service';
import { DatamodelService } from './datamodel.service';
export * from './employee.service';
import { EmployeeService } from './employee.service';
export * from './file.service';
import { FileService } from './file.service';
export * from './group.service';
import { GroupService } from './group.service';
export * from './joblevel.service';
import { JoblevelService } from './joblevel.service';
export * from './menu.service';
import { MenuService } from './menu.service';
export * from './organization.service';
import { OrganizationService } from './organization.service';
export * from './pemgroup.service';
import { PemgroupService } from './pemgroup.service';
export * from './restApiService.service';
import { RestApiServiceService } from './restApiService.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './rule.service';
import { RuleService } from './rule.service';
export * from './scope.service';
import { ScopeService } from './scope.service';
export * from './sysrole.service';
import { SysroleService } from './sysrole.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AuditlogService, DataOrganizationService, DataPermissionService, DatamodelService, EmployeeService, FileService, GroupService, JoblevelService, MenuService, OrganizationService, PemgroupService, RestApiServiceService, RoleService, RuleService, ScopeService, SysroleService, UserService];
