/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Group { 
    readonly modelName?: string;
    readonly createdDate?: Date;
    readonly modifiedDate?: Date;
    readonly createdBy?: string;
    readonly modifiedBy?: string;
    readonly dataPermissionTokenId?: string;
    readonly id?: string;
    code?: string;
    name?: string;
    owner?: string;
    stat?: string;
    isRoot?: boolean;
    type?: Group.TypeEnum;
}
export namespace Group {
    export type TypeEnum = 'USER' | 'ROLE' | 'SYSROLE' | 'EMPLOYEE' | 'LEVEL' | 'ORGANIZATION' | 'GROUP';
    export const TypeEnum = {
        USER: 'USER' as TypeEnum,
        ROLE: 'ROLE' as TypeEnum,
        SYSROLE: 'SYSROLE' as TypeEnum,
        EMPLOYEE: 'EMPLOYEE' as TypeEnum,
        LEVEL: 'LEVEL' as TypeEnum,
        ORGANIZATION: 'ORGANIZATION' as TypeEnum,
        GROUP: 'GROUP' as TypeEnum
    };
}