/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Menu { 
    readonly createdDate?: Date;
    readonly modifiedDate?: Date;
    readonly createdBy?: string;
    readonly modifiedBy?: string;
    readonly modelName?: string;
    readonly dataPermissionTokenId?: string;
    readonly id?: string;
    code?: string;
    name?: string;
    parentId?: string;
    url?: string;
    isSystem?: boolean;
    previousNodeId?: string;
    nextNodeId?: string;
    icon?: string;
}