/**
 * car-boss-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Menu } from './menu';
import { PageableObject } from './pageableObject';
import { SortObject } from './sortObject';

export interface PageMenu { 
    totalPages?: number;
    totalElements?: number;
    sort?: SortObject;
    number?: number;
    size?: number;
    content?: Array<Menu>;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
}