export * from './admin.service';
import { AdminService } from './admin.service';
export * from './attackDetection.service';
import { AttackDetectionService } from './attackDetection.service';
export * from './authenticationManagement.service';
import { AuthenticationManagementService } from './authenticationManagement.service';
export * from './clientAttributeCertificate.service';
import { ClientAttributeCertificateService } from './clientAttributeCertificate.service';
export * from './clientInitialAccess.service';
import { ClientInitialAccessService } from './clientInitialAccess.service';
export * from './clientRegistrationPolicy.service';
import { ClientRegistrationPolicyService } from './clientRegistrationPolicy.service';
export * from './clientRoleMappings.service';
import { ClientRoleMappingsService } from './clientRoleMappings.service';
export * from './clientScopes.service';
import { ClientScopesService } from './clientScopes.service';
export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './component.service';
import { ComponentService } from './component.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './identityProviders.service';
import { IdentityProvidersService } from './identityProviders.service';
export * from './key.service';
import { KeyService } from './key.service';
export * from './protocolMappers.service';
import { ProtocolMappersService } from './protocolMappers.service';
export * from './realmsAdmin.service';
import { RealmsAdminService } from './realmsAdmin.service';
export * from './roleMapper.service';
import { RoleMapperService } from './roleMapper.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './rolesByID.service';
import { RolesByIDService } from './rolesByID.service';
export * from './root.service';
import { RootService } from './root.service';
export * from './scopeMappings.service';
import { ScopeMappingsService } from './scopeMappings.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AdminService, AttackDetectionService, AuthenticationManagementService, ClientAttributeCertificateService, ClientInitialAccessService, ClientRegistrationPolicyService, ClientRoleMappingsService, ClientScopesService, ClientsService, ComponentService, GroupsService, IdentityProvidersService, KeyService, ProtocolMappersService, RealmsAdminService, RoleMapperService, RolesService, RolesByIDService, RootService, ScopeMappingsService, UsersService];
