/**
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ProtocolMapperRepresentation } from '../model/protocolMapperRepresentation';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ProtocolMappersService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Delete the mapper
     * 
     * @param realm realm name (not id!)
     * @param id1 
     * @param id2 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientScopesId1ProtocolMappersModelsId2Delete(realm: string, id1: string, id2: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public realmClientScopesId1ProtocolMappersModelsId2Delete(realm: string, id1: string, id2: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public realmClientScopesId1ProtocolMappersModelsId2Delete(realm: string, id1: string, id2: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public realmClientScopesId1ProtocolMappersModelsId2Delete(realm: string, id1: string, id2: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientScopesId1ProtocolMappersModelsId2Delete.');
        }

        if (id1 === null || id1 === undefined) {
            throw new Error('Required parameter id1 was null or undefined when calling realmClientScopesId1ProtocolMappersModelsId2Delete.');
        }

        if (id2 === null || id2 === undefined) {
            throw new Error('Required parameter id2 was null or undefined when calling realmClientScopesId1ProtocolMappersModelsId2Delete.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/${encodeURIComponent(String(realm))}/client-scopes/${encodeURIComponent(String(id1))}/protocol-mappers/models/${encodeURIComponent(String(id2))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get mapper by id
     * 
     * @param realm realm name (not id!)
     * @param id1 
     * @param id2 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientScopesId1ProtocolMappersModelsId2Get(realm: string, id1: string, id2: string, observe?: 'body', reportProgress?: boolean): Observable<ProtocolMapperRepresentation>;
    public realmClientScopesId1ProtocolMappersModelsId2Get(realm: string, id1: string, id2: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ProtocolMapperRepresentation>>;
    public realmClientScopesId1ProtocolMappersModelsId2Get(realm: string, id1: string, id2: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ProtocolMapperRepresentation>>;
    public realmClientScopesId1ProtocolMappersModelsId2Get(realm: string, id1: string, id2: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientScopesId1ProtocolMappersModelsId2Get.');
        }

        if (id1 === null || id1 === undefined) {
            throw new Error('Required parameter id1 was null or undefined when calling realmClientScopesId1ProtocolMappersModelsId2Get.');
        }

        if (id2 === null || id2 === undefined) {
            throw new Error('Required parameter id2 was null or undefined when calling realmClientScopesId1ProtocolMappersModelsId2Get.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ProtocolMapperRepresentation>('get',`${this.basePath}/${encodeURIComponent(String(realm))}/client-scopes/${encodeURIComponent(String(id1))}/protocol-mappers/models/${encodeURIComponent(String(id2))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update the mapper
     * 
     * @param body 
     * @param realm realm name (not id!)
     * @param id1 
     * @param id2 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientScopesId1ProtocolMappersModelsId2Put(body: ProtocolMapperRepresentation, realm: string, id1: string, id2: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public realmClientScopesId1ProtocolMappersModelsId2Put(body: ProtocolMapperRepresentation, realm: string, id1: string, id2: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public realmClientScopesId1ProtocolMappersModelsId2Put(body: ProtocolMapperRepresentation, realm: string, id1: string, id2: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public realmClientScopesId1ProtocolMappersModelsId2Put(body: ProtocolMapperRepresentation, realm: string, id1: string, id2: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling realmClientScopesId1ProtocolMappersModelsId2Put.');
        }

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientScopesId1ProtocolMappersModelsId2Put.');
        }

        if (id1 === null || id1 === undefined) {
            throw new Error('Required parameter id1 was null or undefined when calling realmClientScopesId1ProtocolMappersModelsId2Put.');
        }

        if (id2 === null || id2 === undefined) {
            throw new Error('Required parameter id2 was null or undefined when calling realmClientScopesId1ProtocolMappersModelsId2Put.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/${encodeURIComponent(String(realm))}/client-scopes/${encodeURIComponent(String(id1))}/protocol-mappers/models/${encodeURIComponent(String(id2))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create multiple mappers
     * 
     * @param body 
     * @param realm realm name (not id!)
     * @param id id of client scope (not name)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientScopesIdProtocolMappersAddModelsPost(body: Array<ProtocolMapperRepresentation>, realm: string, id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public realmClientScopesIdProtocolMappersAddModelsPost(body: Array<ProtocolMapperRepresentation>, realm: string, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public realmClientScopesIdProtocolMappersAddModelsPost(body: Array<ProtocolMapperRepresentation>, realm: string, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public realmClientScopesIdProtocolMappersAddModelsPost(body: Array<ProtocolMapperRepresentation>, realm: string, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling realmClientScopesIdProtocolMappersAddModelsPost.');
        }

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientScopesIdProtocolMappersAddModelsPost.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling realmClientScopesIdProtocolMappersAddModelsPost.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/${encodeURIComponent(String(realm))}/client-scopes/${encodeURIComponent(String(id))}/protocol-mappers/add-models`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get mappers
     * 
     * @param realm realm name (not id!)
     * @param id id of client scope (not name)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientScopesIdProtocolMappersModelsGet(realm: string, id: string, observe?: 'body', reportProgress?: boolean): Observable<Array<{ [key: string]: any; }>>;
    public realmClientScopesIdProtocolMappersModelsGet(realm: string, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<{ [key: string]: any; }>>>;
    public realmClientScopesIdProtocolMappersModelsGet(realm: string, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<{ [key: string]: any; }>>>;
    public realmClientScopesIdProtocolMappersModelsGet(realm: string, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientScopesIdProtocolMappersModelsGet.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling realmClientScopesIdProtocolMappersModelsGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<{ [key: string]: any; }>>('get',`${this.basePath}/${encodeURIComponent(String(realm))}/client-scopes/${encodeURIComponent(String(id))}/protocol-mappers/models`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a mapper
     * 
     * @param body 
     * @param realm realm name (not id!)
     * @param id id of client scope (not name)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientScopesIdProtocolMappersModelsPost(body: ProtocolMapperRepresentation, realm: string, id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public realmClientScopesIdProtocolMappersModelsPost(body: ProtocolMapperRepresentation, realm: string, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public realmClientScopesIdProtocolMappersModelsPost(body: ProtocolMapperRepresentation, realm: string, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public realmClientScopesIdProtocolMappersModelsPost(body: ProtocolMapperRepresentation, realm: string, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling realmClientScopesIdProtocolMappersModelsPost.');
        }

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientScopesIdProtocolMappersModelsPost.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling realmClientScopesIdProtocolMappersModelsPost.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/${encodeURIComponent(String(realm))}/client-scopes/${encodeURIComponent(String(id))}/protocol-mappers/models`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get mappers by name for a specific protocol
     * 
     * @param realm realm name (not id!)
     * @param id id of client scope (not name)
     * @param protocol 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientScopesIdProtocolMappersProtocolProtocolGet(realm: string, id: string, protocol: string, observe?: 'body', reportProgress?: boolean): Observable<Array<{ [key: string]: any; }>>;
    public realmClientScopesIdProtocolMappersProtocolProtocolGet(realm: string, id: string, protocol: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<{ [key: string]: any; }>>>;
    public realmClientScopesIdProtocolMappersProtocolProtocolGet(realm: string, id: string, protocol: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<{ [key: string]: any; }>>>;
    public realmClientScopesIdProtocolMappersProtocolProtocolGet(realm: string, id: string, protocol: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientScopesIdProtocolMappersProtocolProtocolGet.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling realmClientScopesIdProtocolMappersProtocolProtocolGet.');
        }

        if (protocol === null || protocol === undefined) {
            throw new Error('Required parameter protocol was null or undefined when calling realmClientScopesIdProtocolMappersProtocolProtocolGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<{ [key: string]: any; }>>('get',`${this.basePath}/${encodeURIComponent(String(realm))}/client-scopes/${encodeURIComponent(String(id))}/protocol-mappers/protocol/${encodeURIComponent(String(protocol))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete the mapper
     * 
     * @param realm realm name (not id!)
     * @param id1 
     * @param id2 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientsId1ProtocolMappersModelsId2Delete(realm: string, id1: string, id2: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public realmClientsId1ProtocolMappersModelsId2Delete(realm: string, id1: string, id2: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public realmClientsId1ProtocolMappersModelsId2Delete(realm: string, id1: string, id2: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public realmClientsId1ProtocolMappersModelsId2Delete(realm: string, id1: string, id2: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientsId1ProtocolMappersModelsId2Delete.');
        }

        if (id1 === null || id1 === undefined) {
            throw new Error('Required parameter id1 was null or undefined when calling realmClientsId1ProtocolMappersModelsId2Delete.');
        }

        if (id2 === null || id2 === undefined) {
            throw new Error('Required parameter id2 was null or undefined when calling realmClientsId1ProtocolMappersModelsId2Delete.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/${encodeURIComponent(String(realm))}/clients/${encodeURIComponent(String(id1))}/protocol-mappers/models/${encodeURIComponent(String(id2))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get mapper by id
     * 
     * @param realm realm name (not id!)
     * @param id1 
     * @param id2 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientsId1ProtocolMappersModelsId2Get(realm: string, id1: string, id2: string, observe?: 'body', reportProgress?: boolean): Observable<ProtocolMapperRepresentation>;
    public realmClientsId1ProtocolMappersModelsId2Get(realm: string, id1: string, id2: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ProtocolMapperRepresentation>>;
    public realmClientsId1ProtocolMappersModelsId2Get(realm: string, id1: string, id2: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ProtocolMapperRepresentation>>;
    public realmClientsId1ProtocolMappersModelsId2Get(realm: string, id1: string, id2: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientsId1ProtocolMappersModelsId2Get.');
        }

        if (id1 === null || id1 === undefined) {
            throw new Error('Required parameter id1 was null or undefined when calling realmClientsId1ProtocolMappersModelsId2Get.');
        }

        if (id2 === null || id2 === undefined) {
            throw new Error('Required parameter id2 was null or undefined when calling realmClientsId1ProtocolMappersModelsId2Get.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ProtocolMapperRepresentation>('get',`${this.basePath}/${encodeURIComponent(String(realm))}/clients/${encodeURIComponent(String(id1))}/protocol-mappers/models/${encodeURIComponent(String(id2))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update the mapper
     * 
     * @param body 
     * @param realm realm name (not id!)
     * @param id1 
     * @param id2 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientsId1ProtocolMappersModelsId2Put(body: ProtocolMapperRepresentation, realm: string, id1: string, id2: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public realmClientsId1ProtocolMappersModelsId2Put(body: ProtocolMapperRepresentation, realm: string, id1: string, id2: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public realmClientsId1ProtocolMappersModelsId2Put(body: ProtocolMapperRepresentation, realm: string, id1: string, id2: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public realmClientsId1ProtocolMappersModelsId2Put(body: ProtocolMapperRepresentation, realm: string, id1: string, id2: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling realmClientsId1ProtocolMappersModelsId2Put.');
        }

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientsId1ProtocolMappersModelsId2Put.');
        }

        if (id1 === null || id1 === undefined) {
            throw new Error('Required parameter id1 was null or undefined when calling realmClientsId1ProtocolMappersModelsId2Put.');
        }

        if (id2 === null || id2 === undefined) {
            throw new Error('Required parameter id2 was null or undefined when calling realmClientsId1ProtocolMappersModelsId2Put.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/${encodeURIComponent(String(realm))}/clients/${encodeURIComponent(String(id1))}/protocol-mappers/models/${encodeURIComponent(String(id2))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create multiple mappers
     * 
     * @param body 
     * @param realm realm name (not id!)
     * @param id id of client (not client-id)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientsIdProtocolMappersAddModelsPost(body: Array<ProtocolMapperRepresentation>, realm: string, id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public realmClientsIdProtocolMappersAddModelsPost(body: Array<ProtocolMapperRepresentation>, realm: string, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public realmClientsIdProtocolMappersAddModelsPost(body: Array<ProtocolMapperRepresentation>, realm: string, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public realmClientsIdProtocolMappersAddModelsPost(body: Array<ProtocolMapperRepresentation>, realm: string, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling realmClientsIdProtocolMappersAddModelsPost.');
        }

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientsIdProtocolMappersAddModelsPost.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling realmClientsIdProtocolMappersAddModelsPost.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/${encodeURIComponent(String(realm))}/clients/${encodeURIComponent(String(id))}/protocol-mappers/add-models`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get mappers
     * 
     * @param realm realm name (not id!)
     * @param id id of client (not client-id)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientsIdProtocolMappersModelsGet(realm: string, id: string, observe?: 'body', reportProgress?: boolean): Observable<Array<{ [key: string]: any; }>>;
    public realmClientsIdProtocolMappersModelsGet(realm: string, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<{ [key: string]: any; }>>>;
    public realmClientsIdProtocolMappersModelsGet(realm: string, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<{ [key: string]: any; }>>>;
    public realmClientsIdProtocolMappersModelsGet(realm: string, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientsIdProtocolMappersModelsGet.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling realmClientsIdProtocolMappersModelsGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<{ [key: string]: any; }>>('get',`${this.basePath}/${encodeURIComponent(String(realm))}/clients/${encodeURIComponent(String(id))}/protocol-mappers/models`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a mapper
     * 
     * @param body 
     * @param realm realm name (not id!)
     * @param id id of client (not client-id)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientsIdProtocolMappersModelsPost(body: ProtocolMapperRepresentation, realm: string, id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public realmClientsIdProtocolMappersModelsPost(body: ProtocolMapperRepresentation, realm: string, id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public realmClientsIdProtocolMappersModelsPost(body: ProtocolMapperRepresentation, realm: string, id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public realmClientsIdProtocolMappersModelsPost(body: ProtocolMapperRepresentation, realm: string, id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling realmClientsIdProtocolMappersModelsPost.');
        }

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientsIdProtocolMappersModelsPost.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling realmClientsIdProtocolMappersModelsPost.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/${encodeURIComponent(String(realm))}/clients/${encodeURIComponent(String(id))}/protocol-mappers/models`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get mappers by name for a specific protocol
     * 
     * @param realm realm name (not id!)
     * @param id id of client (not client-id)
     * @param protocol 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public realmClientsIdProtocolMappersProtocolProtocolGet(realm: string, id: string, protocol: string, observe?: 'body', reportProgress?: boolean): Observable<Array<{ [key: string]: any; }>>;
    public realmClientsIdProtocolMappersProtocolProtocolGet(realm: string, id: string, protocol: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<{ [key: string]: any; }>>>;
    public realmClientsIdProtocolMappersProtocolProtocolGet(realm: string, id: string, protocol: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<{ [key: string]: any; }>>>;
    public realmClientsIdProtocolMappersProtocolProtocolGet(realm: string, id: string, protocol: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (realm === null || realm === undefined) {
            throw new Error('Required parameter realm was null or undefined when calling realmClientsIdProtocolMappersProtocolProtocolGet.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling realmClientsIdProtocolMappersProtocolProtocolGet.');
        }

        if (protocol === null || protocol === undefined) {
            throw new Error('Required parameter protocol was null or undefined when calling realmClientsIdProtocolMappersProtocolProtocolGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<{ [key: string]: any; }>>('get',`${this.basePath}/${encodeURIComponent(String(realm))}/clients/${encodeURIComponent(String(id))}/protocol-mappers/protocol/${encodeURIComponent(String(protocol))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
