export * from './auditlog.service';
import { AuditlogService } from './auditlog.service';
export * from './competition.service';
import { CompetitionService } from './competition.service';
export * from './crewSubstitution.service';
import { CrewSubstitutionService } from './crewSubstitution.service';
export * from './damageReport.service';
import { DamageReportService } from './damageReport.service';
export * from './dataOrganization.service';
import { DataOrganizationService } from './dataOrganization.service';
export * from './dataPermission.service';
import { DataPermissionService } from './dataPermission.service';
export * from './datamodel.service';
import { DatamodelService } from './datamodel.service';
export * from './dict.service';
import { DictService } from './dict.service';
export * from './employee.service';
import { EmployeeService } from './employee.service';
export * from './equipmentSubstitution.service';
import { EquipmentSubstitutionService } from './equipmentSubstitution.service';
export * from './file.service';
import { FileService } from './file.service';
export * from './group.service';
import { GroupService } from './group.service';
export * from './hearingRequest.service';
import { HearingRequestService } from './hearingRequest.service';
export * from './joblevel.service';
import { JoblevelService } from './joblevel.service';
export * from './kegistration.service';
import { KegistrationService } from './kegistration.service';
export * from './member.service';
import { MemberService } from './member.service';
export * from './menu.service';
import { MenuService } from './menu.service';
export * from './objectStorage.service';
import { ObjectStorageService } from './objectStorage.service';
export * from './organization.service';
import { OrganizationService } from './organization.service';
export * from './pemgroup.service';
import { PemgroupService } from './pemgroup.service';
export * from './penalty.service';
import { PenaltyService } from './penalty.service';
export * from './question.service';
import { QuestionService } from './question.service';
export * from './restApiService.service';
import { RestApiServiceService } from './restApiService.service';
export * from './retirementReport.service';
import { RetirementReportService } from './retirementReport.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './rule.service';
import { RuleService } from './rule.service';
export * from './scope.service';
import { ScopeService } from './scope.service';
export * from './scoringInquiry.service';
import { ScoringInquiryService } from './scoringInquiry.service';
export * from './sysconfig.service';
import { SysconfigService } from './sysconfig.service';
export * from './sysrole.service';
import { SysroleService } from './sysrole.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AuditlogService, CompetitionService, CrewSubstitutionService, DamageReportService, DataOrganizationService, DataPermissionService, DatamodelService, DictService, EmployeeService, EquipmentSubstitutionService, FileService, GroupService, HearingRequestService, JoblevelService, KegistrationService, MemberService, MenuService, ObjectStorageService, OrganizationService, PemgroupService, PenaltyService, QuestionService, RestApiServiceService, RetirementReportService, RoleService, RuleService, ScopeService, ScoringInquiryService, SysconfigService, SysroleService, UserService];
