export * from './competition.service';
import { CompetitionService } from './competition.service';
export * from './crewSubstitution.service';
import { CrewSubstitutionService } from './crewSubstitution.service';
export * from './damageReport.service';
import { DamageReportService } from './damageReport.service';
export * from './dict.service';
import { DictService } from './dict.service';
export * from './equipmentSubstitution.service';
import { EquipmentSubstitutionService } from './equipmentSubstitution.service';
export * from './hearingRequest.service';
import { HearingRequestService } from './hearingRequest.service';
export * from './kegistration.service';
import { KegistrationService } from './kegistration.service';
export * from './member.service';
import { MemberService } from './member.service';
export * from './penaltyReport.service';
import { PenaltyReportService } from './penaltyReport.service';
export * from './question.service';
import { QuestionService } from './question.service';
export * from './retirementReport.service';
import { RetirementReportService } from './retirementReport.service';
export * from './scoringInquiry.service';
import { ScoringInquiryService } from './scoringInquiry.service';
export const APIS = [CompetitionService, CrewSubstitutionService, DamageReportService, DictService, EquipmentSubstitutionService, HearingRequestService, KegistrationService, MemberService, PenaltyReportService, QuestionService, RetirementReportService, ScoringInquiryService];
